/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.HospitalDao;
import dao.PersonDao;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.hospitals.Hospital;
import model.hospitals.HospitalDir;
import model.persons.Doctor;
import model.persons.DoctorDir;
import model.persons.PersonDir;

/**
 *
 * @author Jiaf
 */
public class DoctorListFrame extends javax.swing.JFrame {

    /**
     * Creates new form DoctorListFrame
     */
    private int hosId = 0;
    
    public DoctorListFrame(){}
    public DoctorListFrame(Hospital h) throws SQLException {
        
        initComponents();
        hosId = h.getHosId();
        populateTable();
        
    }
    
    private void populateTable() throws SQLException{
        try{
            DoctorDir docs = PersonDao.findDocsByHos(hosId);
            DefaultTableModel model = (DefaultTableModel) tblDocs.getModel();

            model.setRowCount(0);

            for (Doctor d : docs.getDoctorDir()){

                Object [] row = new Object[3];
                row[0] = d;
                row[1] = d.getMajor();
                row[2] = d.getWorkTime();

                model.addRow(row);
            }
        }catch(SQLException e){
            
        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDocs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doctor", "Major", "Working Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDocs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDocs;
    // End of variables declaration//GEN-END:variables
}
