/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Jiaf
 */
public class RoleFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form RoleFrame
     */
    public RoleFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbPatient = new javax.swing.JLabel();
        lbDoctor = new javax.swing.JLabel();
        lbComAdm = new javax.swing.JLabel();
        lbSysAdm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Login Role");
        setBackground(new java.awt.Color(0, 51, 102));
        setIconImages(null);
        setLocation(new java.awt.Point(400, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(241, 250, 238));

        jLabel1.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 72, 197));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Hospital Management System!");

        jLabel2.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 123, 157));
        jLabel2.setText("Please tell us who are you?");

        lbPatient.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        lbPatient.setForeground(new java.awt.Color(29, 53, 87));
        lbPatient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/patient.png"))); // NOI18N
        lbPatient.setText("Patient");
        lbPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPatientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPatientMouseExited(evt);
            }
        });

        lbDoctor.setFont(lbPatient.getFont());
        lbDoctor.setForeground(new java.awt.Color(29, 53, 87));
        lbDoctor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doctor.png"))); // NOI18N
        lbDoctor.setText("Doctor");
        lbDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDoctorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDoctorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDoctorMouseExited(evt);
            }
        });

        lbComAdm.setFont(lbPatient.getFont());
        lbComAdm.setForeground(new java.awt.Color(29, 53, 87));
        lbComAdm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbComAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comAdmin.png"))); // NOI18N
        lbComAdm.setText("Community Administar");
        lbComAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbComAdmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbComAdmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbComAdmMouseExited(evt);
            }
        });

        lbSysAdm.setFont(lbPatient.getFont());
        lbSysAdm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSysAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        lbSysAdm.setText("System Manager");
        lbSysAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSysAdmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSysAdmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSysAdmMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSysAdm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbComAdm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDoctor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbComAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSysAdm)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbComAdm, lbDoctor, lbPatient, lbSysAdm});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPatientMouseEntered
        lbPatient.setForeground(Color.decode("#E63946"));        // TODO add your handling code here:
    }//GEN-LAST:event_lbPatientMouseEntered

    private void lbPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPatientMouseExited
        lbPatient.setForeground(Color.black);
    }//GEN-LAST:event_lbPatientMouseExited

    private void lbDoctorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDoctorMouseEntered
        // TODO add your handling code here:
        lbDoctor.setForeground(Color.decode("#E63946"));    
    }//GEN-LAST:event_lbDoctorMouseEntered

    private void lbDoctorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDoctorMouseExited
        // TODO add your handling code here:
        lbDoctor.setForeground(Color.black);
    }//GEN-LAST:event_lbDoctorMouseExited

    private void lbComAdmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbComAdmMouseEntered
        // TODO add your handling code here:        
        lbComAdm.setForeground(Color.decode("#E63946")); 
    }//GEN-LAST:event_lbComAdmMouseEntered

    private void lbComAdmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbComAdmMouseExited
        // TODO add your handling code here:
        lbComAdm.setForeground(Color.black);
    }//GEN-LAST:event_lbComAdmMouseExited

    private void lbSysAdmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSysAdmMouseEntered
        // TODO add your handling code here:
        lbSysAdm.setForeground(Color.decode("#E63946"));  
    }//GEN-LAST:event_lbSysAdmMouseEntered

    private void lbSysAdmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSysAdmMouseExited
        // TODO add your handling code here:
        lbSysAdm.setForeground(Color.black);
    }//GEN-LAST:event_lbSysAdmMouseExited

    private void lbPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPatientMouseClicked
        
        LoginJFrame login = new LoginJFrame("patient");
        login.setVisible(true);
        
    }//GEN-LAST:event_lbPatientMouseClicked

    private void lbDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDoctorMouseClicked
        // TODO add your handling code here:
        
        LoginJFrame login = new LoginJFrame("doctor");
        login.setVisible(true);
    }//GEN-LAST:event_lbDoctorMouseClicked

    private void lbComAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbComAdmMouseClicked
        // TODO add your handling code here:
        LoginJFrame login = new LoginJFrame("comAdmin");
        login.setVisible(true);
    }//GEN-LAST:event_lbComAdmMouseClicked

    private void lbSysAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSysAdmMouseClicked
        // TODO add your handling code here:
        LoginJFrame login = new LoginJFrame("sysAdmin");
        login.setVisible(true);
    }//GEN-LAST:event_lbSysAdmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbComAdm;
    private javax.swing.JLabel lbDoctor;
    private javax.swing.JLabel lbPatient;
    private javax.swing.JLabel lbSysAdm;
    // End of variables declaration//GEN-END:variables
}
